version: '3'
services:
  
  bikeshop.identity:
    container_name: bikeshop-identity
    build: 
      context: BikeShop.Identity
      dockerfile: Dockerfile
    image: kpssnik/bikeshop.identity
    hostname: bikeshop.identity
    ports: 
      - 5001:80
    restart: on-failure

  bikeshop.products:
    container_name: bikeshop-products
    build:
      context: BikeShop.Products
      dockerfile: Dockerfile
    image: kpssnik/bikeshop.products
    hostname: bikeshop.products
    ports: 
      - 5002:80
    restart: on-failure

  bikeshop.service:
    container_name: bikeshop-service
    build:
      context: BikeShop.Service
      dockerfile: Dockerfile
    image: kpssnik/bikeshop.service
    hostname: bikeshop.service
    ports: 
      - 5003:80
    restart: on-failure

  bikeshop.gateway:
    container_name: bikeshop-gateway
    build:
      context: BikeShop.Gateway
      dockerfile: Dockerfile
    image: kpssnik/bikeshop.gateway
    hostname: bikeshop.gateway
    ports:
      - 5000:80
    restart: on-failure 
    links:
      - bikeshop.identity
      - bikeshop.products
      - bikeshop.service
    depends_on:
      - bikeshop.identity
      - bikeshop.products
      - bikeshop.service


  
    
    